title: OpenEAC Alliance
description: "Repository for M&V methodology for EACs in WEATS"
theme: jekyll-theme-primer
markdown: kramdown
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "approved_documents/methodologies"
      type: "pages"
    values:
      layout: redirect
      redirect_to: "https://raw.githubusercontent.com/wattcarbon/open-eac-alliance/main/"
plugins:
  - jekyll-redirect-from
include: ['_pages']
exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
